name: pydecon
channels:
  - defaults
  - anaconda
  - conda-forge
  - david-hoffman
dependencies:
  - python>=3.8
  - numpy
  - pyotf
  - tqdm
  - pip
  - pip:
      - pyfftw
      - dphutils
      - dphplotting
      - peaks
